### ISSUE TITLE
Change http references to https

### ISSUE THREAD

**Issue by fuglede** [cryptopartydk/cryptoparty.dk#21]
I noticed that the email confirmation email contains a bunch of http links, which is not very cryptographically friendly. As far as I can tell (from https://stackoverflow.com/questions/25824598/django-allauth-not-sending-links-with-https in particular), changing this amounts to setting a few environment variables for allauth.

**Comment by valberg** [comment]
Seems to be fixed by upgrading django and django-allauth.
