### ISSUE TITLE
Fix link in cryptoparty creation emails

### ISSUE THREAD

**Issue by fuglede** [cryptopartydk/cryptoparty.dk#22]
Currently, https://github.com/cryptopartydk/cryptoparty.dk/blob/master/parties/templates/parties/email/new_party.txt#L12 just has a placeholder <code><LINK></code>. This seems unintentional?

**Comment by valberg** [comment]
Fixed in https://github.com/cryptopartydk/cryptoparty.dk/commit/d72cefa10199777fc29b8416a979f312ac2c0c2f
